In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [11]:
# Importing the dataset
dataset = pd.read_csv('dataset/multi-linear-regression.csv')
array=dataset.values
X=array[:,0:4]
y=array[:,4]


In [12]:
# Print X,y
print(dataset.shape)
print(X.shape)
print(y.shape)

(50, 5)
(50, 4)
(50,)


In [13]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
#Check X after encoding of 'State' variable
print(X.shape)
X[0:3,:]


(50, 4)


array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1]], dtype=object)

In [14]:
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

In [17]:
#Check X after introducing dummy variable
print(X.shape)
X[0:3,:]

(50, 5)


array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05]])

In [40]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]
print(X.shape)
X[0:3,:]
# 1st column is dropped

(50, 3)


array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54]])

In [19]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [20]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [23]:
y_pred

array([103615.70496732, 132245.69745432, 133070.23906339,  72592.46097845,
       179075.96157176, 116014.3380813 ,  67853.79186105,  98837.47482921,
       114480.26282341, 168492.58649243])

In [24]:
y_test

array([103282.38, 144259.4, 146121.95, 77798.83, 191050.39, 105008.31,
       81229.06, 97483.56, 110352.25, 166187.94], dtype=object)

In [25]:
#Mean deviation
sum(abs(y_pred-y_test))/len(y_pred)

7474.740626469119

In [26]:
# Fitting SVR to the dataset
from sklearn.svm import SVR
regressor2 = SVR(kernel = 'rbf')
regressor2.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [42]:
# Predicting the Test set results
y_pred = regressor2.predict(X_test)


In [29]:
 y_pred

array([107978.19, 107978.19, 107978.19, 107978.19, 107978.19, 107978.19,
       107978.19, 107978.19, 107978.19, 107978.19])

In [30]:
y_test

array([103282.38, 144259.4, 146121.95, 77798.83, 191050.39, 105008.31,
       81229.06, 97483.56, 110352.25, 166187.94], dtype=object)

In [31]:
#Mean deviation
sum(abs(y_pred-y_test))/len(y_pred)

29316.979000000003

In [32]:
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor3 = DecisionTreeRegressor(random_state = 0)
regressor3.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [33]:
# Predicting the Test set results
y_pred = regressor3.predict(X_test)
y_pred

array([101004.64, 141585.52, 141585.52,  78239.91, 182901.99, 105733.54,
        71498.49,  99937.59, 105733.54, 182901.99])

In [34]:
y_test

array([103282.38, 144259.4, 146121.95, 77798.83, 191050.39, 105008.31,
       81229.06, 97483.56, 110352.25, 166187.94], dtype=object)

In [35]:
#Mean deviation
sum(abs(y_pred-y_test))/len(y_pred)

5232.012000000004

In [36]:
# Fitting Random Forest Regression to the dataset
from sklearn.ensemble import RandomForestRegressor
regressor4 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor4.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
# Predicting the Test set results
y_pred = regressor4.predict(X_test)
y_pred

array([102757.47 , 136826.538, 136826.538,  80593.078, 179334.094,
       116665.913,  71594.594, 101257.17 , 112816.246, 171603.813])

In [38]:
y_test

array([103282.38, 144259.4, 146121.95, 77798.83, 191050.39, 105008.31,
       81229.06, 97483.56, 110352.25, 166187.94], dtype=object)

In [39]:
#Mean deviation
sum(abs(y_pred-y_test))/len(y_pred)

6470.927600000001